controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

property_page:
    path: /property
    controller: App\Controller\PropertyController::index

property.show:
    path: '/properties/{id}'
    controller: App\Controller\PropertyController::show

admin_routes:
    resource: App\Controller\Admin\AdminController
    type: annotation

admin_index:
    path: /admin/
    methods: ['GET']
    defaults:
        _controller: 'App\Controller\Admin\AdminController::index'
        _locale: 'en'
    requirements:
        _locale: en|fr

admin_edit:
    path: /admin/{id}
    methods: ['GET', 'POST']
    defaults:
        _controller: 'App\Controller\Admin\AdminController::edit'
    requirements:
        id: \d+

admin_new:
    path: '/admin/create/'
    defaults:
        _controller: 'App\Controller\Admin\AdminController::new'
    methods: ['GET', 'POST']

admin_delete:
    path: /admin/delete/{id}
    controller: 'App\Controller\Admin\AdminController::delete'
    methods: [DELETE, POST]
